// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lidsdymtwltwsakeyewg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpZHNkeW10d2x0d3Nha2V5ZXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwMTYwNzMsImV4cCI6MjA5MDU5MjA3M30.xdlP51QLSD39is1waJsvpi3uuhKEMyRFldRheCwSbSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});